"use client";

import { motion } from "framer-motion";
import { Target, AlertTriangle, Lightbulb } from "lucide-react";

const mission = {
  title: "Mission",
  text: "Our think tank mission is to tackle unemployment by leveraging tourism to create sustainable jobs, empower communities, and unlock long-term economic opportunity.",
  icon: Target,
};

const polarCards = [
  {
    title: "Problem Statement",
    text: "In Kicukiro District, many people — especially youth and women — struggle to secure stable work even as Rwanda\u2019s tourism sector expands. Youth unemployment sits at about 20.5%, while travel and tourism supported roughly 386,000 jobs nationally in 2024. Yet in Kicukiro, much of the value generated by visitors doesn\u2019t translate into consistent income for local residents and small businesses. This gap persists due to skills gaps, limited access to customers and capital, and weak links between tourism demand and youth-led community services.",
    icon: AlertTriangle,
  },
  {
    title: "Solution",
    text: "ThinkSphere is a web-based tourism employment accelerator that recruits and trains youth in hospitality and digital skills, places them through competitions and employer matching, and issues verified credentials that prove job-readiness to recruiters — creating a self-sustaining pipeline where graduates launch businesses that hire more alumni.",
    icon: Lightbulb,
  },
];

export function AboutSection() {
  const MissionIcon = mission.icon;

  return (
    <section id="about" className="relative py-24 md:py-32 px-6 md:px-12 bg-gradient-to-br from-[#FAFAFA] via-white to-[#F5F0E8]/20 overflow-hidden">
      <div className="absolute top-0 right-0 w-[350px] h-[350px] rounded-full bg-[#2A7D6E]/5 blur-[100px] pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-[250px] h-[250px] rounded-full bg-[#1A3A5C]/4 blur-[80px] pointer-events-none" />

      <div className="relative max-w-[1200px] mx-auto">
        {/* Section header — LEFT-ALIGNED */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.5 }}
          transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
          className="text-left mb-14 max-w-[520px]"
        >
          <span className="accent-font inline-block text-[11px] font-bold uppercase tracking-[5px] text-slate-500 mb-4">
            Who We Are
          </span>
          <h2 className="font-serif text-[clamp(1.8rem,4vw,2.4rem)] font-bold tracking-tight text-black mb-4">
            Our Mission
          </h2>
          <p className="font-gotham text-slate-800 text-base leading-relaxed">
            Five ALU students building a system that connects Kicukiro&apos;s youth to Rwanda&apos;s booming tourism industry.
          </p>
        </motion.div>

        {/* Mission Card — full width banner */}
        <motion.div
          initial={{ opacity: 0, x: -60 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true, amount: 0.3 }}
          transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
          className="mb-8"
        >
          <div className="glass-panel liquid-glass-hover p-7 text-left">
            <div className="flex items-start gap-5">
              <div className="w-10 h-10 rounded-xl glass-panel flex items-center justify-center shrink-0">
                <MissionIcon className="w-4.5 h-4.5 text-[#2A7D6E]" strokeWidth={1.5} />
              </div>
              <div>
                <h3 className="font-gotham text-[15px] font-bold mb-2.5 text-black">{mission.title}</h3>
                <p className="font-gotham text-sm text-slate-800 leading-relaxed">{mission.text}</p>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Polar Opposites — Problem LEFT, Solution RIGHT with breathing room */}
        <div className="grid grid-cols-1 md:grid-cols-12 gap-5">
          {polarCards.map((c, i) => {
            const Icon = c.icon;
            const isLeft = i === 0;
            return (
              <motion.div
                key={c.title}
                initial={{ opacity: 0, x: isLeft ? -60 : 60 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true, amount: 0.3 }}
                transition={{
                  duration: 0.6,
                  ease: [0.16, 1, 0.3, 1],
                  delay: i * 0.15,
                }}
                className={
                  isLeft
                    ? "md:col-span-5 md:col-start-1"   // Problem: anchored LEFT
                    : "md:col-span-5 md:col-start-8"   // Solution: anchored RIGHT
                }
              >
                <div className="glass-panel liquid-glass-hover p-7 h-full text-left">
                  <div className="w-10 h-10 rounded-xl glass-panel flex items-center justify-center mb-5">
                    <Icon className="w-4.5 h-4.5 text-[#2A7D6E]" strokeWidth={1.5} />
                  </div>
                  <h3 className="font-gotham text-[15px] font-bold mb-2.5 text-black">{c.title}</h3>
                  <p className="font-gotham text-sm text-slate-800 leading-relaxed">{c.text}</p>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
